name:                snek
version:             0.1.0.0
github:              cymerrad/snek
license:             BSD3
author:              Rado Cymer
maintainer:          cymerrad@gmail.com
copyright:           2023 Author name here

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/snek#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.12.0
- brick
- vty
- microlens
- microlens-mtl
- microlens-th
- aeson
- aeson-pretty
- bytestring
- random
- word-wrap

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  snek-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - snek
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  snek-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - snek
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
